update 2019
shagalalab/sozlik-web pull request #5
Opened 2019-05-27 19:47 UTC by ikhasanmusaev

we updated the database and added small flags

2019-05-28 11:38 UTC, atabekm requested changes
Funkcional jaginan hammesi izlep turipti zor 👍, tek mayda shuyde kemshilikler bar eken, solardi korip shigarsan.

2019-05-28 11:38 UTC, atabekm commented on sozik.py
> +    cur.execute("select type from dictionary where word like ? limit 10", (beginswith + '%',))
Bul jerde ekinshi ret qaytadan zapros jiberiw artiqsha, sebebi `type` ti aldingi zaprostin ozindede alsan boladi. SQL query'de:
`SELECT [column(s)] FROM [table_name]`
Bul jerde `[column(s)]` ta tablicadagi bir, eki ya barliq column'lardi korsetiwge boladi, `*` desen barliq column'lardi qaytaradi, tek sheklengeni kerek bolsa onda utir qoyip jazip keteberesen. Sonda bul metodta tek bir qatarda gana ozgeris kerek boladi

2019-05-28 11:38 UTC, atabekm commented on static/css/style.css
> +/*}*/
minaw kerek emes bolsa oshirip tasla, quri comment out qilingannan oshirip taslagan jaqsi. Uliwma islep atirgan waqtinda comment qilip tursan boladida, bolganinnan keyin kerek emes bolsa oshirip taslaw kerek. Basqa jerlerdede sondaylar bolsa olardida durislap ket.

2019-05-28 11:38 UTC, atabekm commented on static/css/style.css
> +/*ul a li*/
minanida

2019-05-28 11:38 UTC, atabekm commented on static/css/style.css
> +
bos qatarlardi oshirip tasla, onnan keyin flag'lar dim onga taqalip qalgan, soni tomendegi suwrette korsetilgen qizil siziqtin shep jagina qoya alasanba?
<img width="688" alt="sozlik-suggestion" src="https://user-images.githubusercontent.com/8268042/58473017-ee993a00-818a-11e9-9db8-7ec1ed96c763.png">

2019-05-28 11:38 UTC, atabekm commented on sozik.py
> +    return jsonify(suggestions=data, type=data1)
mina jerde sonda eki bolek danniy bermesten, sol aldingi turisinda quri `data` ni bereberesen. Biraq endi data quri string array emes, al dictionary array boladi, dictionary haqqinda oqip kor, tusinbesen aytarsan.

2019-05-28 11:38 UTC, atabekm commented on templates/index.html
> +                        var item1 = data.type[i];
joqaridagi ozgerislerden keyin bul jerde ozgeris boladi

2019-05-28 11:38 UTC, atabekm commented on templates/translate.html
> +                <div>
mina div artiqsha bolip ketken

2019-05-28 11:38 UTC, atabekm commented on templates/translate.html
> +                    <p><img src={{ img_src }} height="22" width="90"></p>
`width` kerek emes, ozinin uzinligi jetedi, soytip flag sozdin astina tigilip ketken, soni soz benen tomengi shegaranin ortasina qoya alasanba?

<img width="314" alt="sozlik-flag" src="https://user-images.githubusercontent.com/8268042/58474591-f529b080-818e-11e9-84c8-e82e81fc5c9b.png">

2019-05-28 11:38 UTC, atabekm commented on static/css/style.css
>  }
mina blok kerek emes

2019-05-28 11:38 UTC, atabekm commented on static/css/style.css
> +    color: white;
mina aqti alip taslamasan social icon'lar korinbey qalip atir eken aq bolip

2019-05-28 11:55 UTC, ikhasanmusaev commented on sozik.py
> +    cur.execute("select type from dictionary where word like ? limit 10", (beginswith + '%',))
awa ózimam oyladım,  budan qabarım bar edi. cursordan fetchall day qılıp qanday qılıp alıwdı oylanǵannan kóre jazaqoyıp edim durıslawǵa háreket qılaman

2019-05-28 11:56 UTC, ikhasanmusaev commented on static/css/style.css
> +/*}*/
yaqshı, umıtıp ketippen

2019-05-28 11:56 UTC, ikhasanmusaev commented on static/css/style.css
> +
háreket qılaman

2019-05-31 11:09 UTC, atabekm requested changes

2019-05-31 11:09 UTC, atabekm commented on templates/footer.html
> +                    <div class="copyright pull-right">Copyright &copy; 2019 <a href="http://www.shagalalab.com">Shaǵala Lab</a></div>
Mina jerde aldingi jazganin duris edi, 2017 - 2019 dep turabersin

2019-05-31 11:09 UTC, atabekm commented on templates/index.html
> +                        if (item['type'] == '1')
bul jerde ulken problema emes, biraq `if else` bloklardi adette {}'lar menen oragan jaqsi, keleshekte qatelerdin aldin aliw ushin. Hazir problemasiz isleydi, biraq keyin bilmey skobkasiz ekinshi qatar qosip jibersen, sonin menen kop waqtindi sariplap otiriwin mumkin, nege gozlengenindey islemey atir dep. Sogan `if else` bolama, ya basqa bloklar bolama `{}` menen oragan jaqsi, bir qatar bolsada.

2019-05-31 11:09 UTC, atabekm commented on templates/index.html
>                              n = '/ruqq.png';
minani aldin kormey qalippan, biraq ozgerishinin atamasin tusinikli qilip qoyiw kerek, bul jerde maselen quri `n` degennin ne ekenin tusiniw qiyin. Sonin ushin meninshe `flag_image` ya sogan qusagan bir at qoysan tawirlew boladi, bir qaraganda ne ekenin tusinip alatuginday.

2019-05-31 11:28 UTC, atabekm approved these changes

2019-05-31 11:30 UTC, merged